{
"Ted Lasso",
"Boba Fett",
"Veronica Mars",
"Barney Stinson",
"SpongeBob SquarePants",
"Don Draper",
"Saul Goodman",
"Miranda Priestly",
"Dexter Morgan",
"Tina Belcher",
"Aang",
"BoJack Horseman",
"Kramer",
"Katniss Everdeen",
"Sheldon Cooper",
"Daria Morgendorffer",
"Philip J. Fry",
"Lisa Simpson",
"Eric Cartman",
"Jake Peralta",
"Geralt of Rivia",
"Jean-Luc Picard",
"Mulder",
"Lorelai Gilmore",
"Willy Wonka",
"Walter White",
"Frodo Baggins",
"Tony Stark",
"Arya Stark",
"Indiana Jones",
"Marty McFly",
"Lara Croft",
"Rick Grimes",
"Ellen Ripley",
"Sherlock Holmes",
"Michael Scott",
"Buffy Summers",
"Jack Sparrow",
"Eleven",
"Darth Vader",
"Yoda",
"Peter Parker",
"Daenerys Targaryen",
"Neo",
"Hannibal Lecter",
"Jon Snow",
"Bruce Wayne",
"Wanda Maximoff",
"The Doctor",
"Gollum"
}
